In [ ]:
!pip install numpy   #installing numpy lib

# NUMPY

### WHAT IS NUMPY?

<b>NUMPY </b> stands for Numerical Python. It is Python library used for working with <b>Scientific Computing,Multi-dimensional arrays and Matrices. </b>

In [1]:
import numpy as np

##### VERSION

In [2]:
np.__version__

'1.16.2'

#### Array_Creation

In [3]:
a=np.array([5,7,9])

In [4]:
a.dtype

dtype('int32')

In [5]:
type([5,7,9])

list

In [6]:
#2 dimensions

In [7]:
a=np.array([[1,2],[3,4],[5,8]])

In [8]:
a

array([[1, 2],
       [3, 4],
       [5, 8]])

#### Converting int to float 

In [9]:
#dtype
a=np.array([1,2,3],dtype=float)
a

array([1., 2., 3.])

In [10]:
a=[1,2,3,4]
np.asfarray(a)

array([1., 2., 3., 4.])

#### Converting into array using .mat[Matrix]

In [11]:
np.array(np.mat('1,2,3;3,4,5'))                #check

array([[1, 2, 3],
       [3, 4, 5]])

In [12]:
#Creating a list into np_array

In [13]:
a=[1,2,3]
np.array(a)

array([1, 2, 3])

In [14]:
np.asarray(a)

array([1, 2, 3])

### data type

In [15]:
a=[1,2,3]
print("Class/Type of this object:   ",type(np.array(a)))
print("Here the vectors are:\n-------------\n",np.array(a))

Class/Type of this object:    <class 'numpy.ndarray'>
Here the vectors are:
-------------
 [1 2 3]


In [16]:
a=[[1,2,3],[3,4,5],[5,6,7]]
mat=np.array(a)
print("Class/Type of the object:   ",type(mat))
print("Heres the vector are:\n--------\n",mat)
print("Dimension:  ",mat.ndim)
print("Size of each element in mat:  ",mat.itemsize,"byte")
print("Length of mat:  ",mat.size)
print("Shape of mat:  ",mat.shape)
print("Data Type of mat:  ",mat.dtype)

Class/Type of the object:    <class 'numpy.ndarray'>
Heres the vector are:
--------
 [[1 2 3]
 [3 4 5]
 [5 6 7]]
Dimension:   2
Size of each element in mat:   4 byte
Length of mat:   9
Shape of mat:   (3, 3)
Data Type of mat:   int32


### arange and linspace

###### range v/s np.arange

In [17]:
list(range(2,10.4,0.4))  #Throw error becoz range only works with integer

TypeError: 'float' object cannot be interpreted as an integer

In [18]:
a=np.arange(2,10.4,0.4)     #while it works with integer as well as float
a.dtype

dtype('float64')

In [19]:
a

array([ 2. ,  2.4,  2.8,  3.2,  3.6,  4. ,  4.4,  4.8,  5.2,  5.6,  6. ,
        6.4,  6.8,  7.2,  7.6,  8. ,  8.4,  8.8,  9.2,  9.6, 10. ])

In [20]:
a[::-1]

array([10. ,  9.6,  9.2,  8.8,  8.4,  8. ,  7.6,  7.2,  6.8,  6.4,  6. ,
        5.6,  5.2,  4.8,  4.4,  4. ,  3.6,  3.2,  2.8,  2.4,  2. ])

In [21]:
np.arange(50,-1,-5)

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5,  0])

##### linspace

In [22]:
print("Linearly spaced range:\n----------\n")
np.linspace(10,40,5)

Linearly spaced range:
----------



array([10. , 17.5, 25. , 32.5, 40. ])

In [24]:
np.linspace(2.0,3.0,num=4,endpoint=False)    #EndPoint setted to True it means it includes the last value

array([2.  , 2.25, 2.5 , 2.75])

In [25]:
np.linspace(2.234,10.256,num=10,endpoint=True,retstep=True) #Here retstep gives the step_size

(array([ 2.234     ,  3.12533333,  4.01666667,  4.908     ,  5.79933333,
         6.69066667,  7.582     ,  8.47333333,  9.36466667, 10.256     ]),
 0.8913333333333333)

#### Matrix Creation

In [26]:
print("Vectors are:\n--------\n",np.array(np.zeros(5)))

Vectors are:
--------
 [0. 0. 0. 0. 0.]


In [27]:
print("Matrix of zeroes:\n--------------\n",np.array(np.zeros((5,3))))

Matrix of zeroes:
--------------
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [28]:
print("Vectors are:\n------------\n",np.ones(4))

Vectors are:
------------
 [1. 1. 1. 1.]


In [29]:
print("Matrix of ones:\n-------------------------\n",np.ones((5,3)))

Matrix of ones:
-------------------------
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [30]:
n=467
print("Matrix of n no.\n-----------------\n",n*np.ones((5,3)))

Matrix of n no.
-----------------
 [[467. 467. 467.]
 [467. 467. 467.]
 [467. 467. 467.]
 [467. 467. 467.]
 [467. 467. 467.]]


### Identity Matrix

In [31]:
a=np.eye(5)
print("Ceated an Identity Matrix of order: ",a.shape,"\n-------------\nThe Identity Matrix is:\n-------------\n",a)

Ceated an Identity Matrix of order:  (5, 5) 
-------------
The Identity Matrix is:
-------------
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [32]:
a=5*a
a

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

##### Reshape

In [33]:
a.reshape(25,1)

array([[5.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [5.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [5.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [5.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [5.]])

In [34]:
import numpy as np
import numpy.random as nr
print("Random number generation(from uniform distribution)\n",'-'*30,'\nMaintains Consistancy\n','-'*30)
nr.rand(5,2)

Random number generation(from uniform distribution)
 ------------------------------ 
Maintains Consistancy
 ------------------------------


array([[0.06926464, 0.37405818],
       [0.17142612, 0.4312807 ],
       [0.11820426, 0.52842736],
       [0.06189586, 0.21900192],
       [0.96234731, 0.27882655]])

In [35]:
print("Random No. Generation with mean approx zero and standard deviation 1 (from Normal Distribution)\n",'-'*30,'\n')
nr.randn(5,5)

Random No. Generation with mean approx zero and standard deviation 1 (from Normal Distribution)
 ------------------------------ 



array([[-0.60050413, -1.55033936, -1.86187457,  0.63232331, -1.16874167],
       [-0.61645203, -1.05716631, -0.42081766, -1.15444429, -0.27441301],
       [-1.49377744,  0.34905339,  1.26606354, -0.90230468, -0.39329217],
       [ 0.03534188, -0.43370029, -0.33453586,  1.24823905,  0.21498026],
       [ 0.21788608, -0.91113191,  0.29245465, -0.7206416 ,  1.28630865]])

In [36]:
print("Random integer vector\n",'-'*30,'\n')
nr.randint(1,7,30)  #randint(starting point[included],ending point[excluded],no. of variable)

Random integer vector
 ------------------------------ 



array([4, 5, 3, 4, 3, 3, 2, 3, 6, 1, 3, 1, 5, 6, 1, 4, 5, 3, 1, 4, 4, 5,
       4, 6, 4, 3, 5, 2, 4, 4])

## Reshaping

In [37]:
a=nr.randint(1,8,20).reshape(5,4)

In [38]:
a

array([[4, 5, 5, 6],
       [6, 5, 1, 3],
       [7, 5, 7, 4],
       [1, 7, 3, 7],
       [3, 6, 3, 1]])

In [39]:
a.reshape(2,2,5)

array([[[4, 5, 5, 6, 6],
        [5, 1, 3, 7, 5]],

       [[7, 4, 1, 7, 3],
        [7, 3, 6, 3, 1]]])

## Sorting

In [40]:
a=nr.randint(1,100,25)
print("Vectors of a are:\n",'-'*30,'\n',a)
print("\nSorted Vectors of a:\n",'-'*30,'\n',np.sort(a,kind='mergesort'))
b=a.reshape(5,5)
print("\n\nSorted vector throgh Row:\n",'-'*30,'\n',np.sort(b,kind='quicksort'))
print("\n\nSorted vector throgh column:\n",'-'*30,'\n',np.sort(b,axis=0,kind='quicksort'))

Vectors of a are:
 ------------------------------ 
 [79 10 40  8 37 11 95 28 94 72 73 25 28 71 43 25 67 83 28 47 50 54  3 71
 89]

Sorted Vectors of a:
 ------------------------------ 
 [ 3  8 10 11 25 25 28 28 28 37 40 43 47 50 54 67 71 71 72 73 79 83 89 94
 95]


Sorted vector throgh Row:
 ------------------------------ 
 [[ 8 10 37 40 79]
 [11 28 72 94 95]
 [25 28 43 71 73]
 [25 28 47 67 83]
 [ 3 50 54 71 89]]


Sorted vector throgh column:
 ------------------------------ 
 [[11 10  3  8 37]
 [25 25 28 28 43]
 [50 54 28 71 47]
 [73 67 40 71 72]
 [79 95 83 94 89]]


In [41]:
print("Max of matrix:",np.max(b),"\nMin of matrix:",np.min(b))

Max of matrix: 95 
Min of matrix: 3


# Indexing & Slicing

In [42]:
arr=np.arange(0,11)
print("Element at 7th index:",arr[7])

Element at 7th index: 7


In [43]:
print("Element upto 6th index",arr[:7])

Element upto 6th index [0 1 2 3 4 5 6]


In [44]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [45]:
arr[2:8]

array([2, 3, 4, 5, 6, 7])

In [46]:
arr[-1::-2]

array([10,  8,  6,  4,  2,  0])

In [47]:
arr[-1:-9:-2]

array([10,  8,  6,  4])

In [52]:
b

array([[79, 10, 40,  8, 37],
       [11, 95, 28, 94, 72],
       [73, 25, 28, 71, 43],
       [25, 67, 83, 28, 47],
       [50, 54,  3, 71, 89]])

In [53]:
print("matrix slicing:\n",b[:])

matrix slicing:
 [[79 10 40  8 37]
 [11 95 28 94 72]
 [73 25 28 71 43]
 [25 67 83 28 47]
 [50 54  3 71 89]]


In [54]:
b[1][3]

94

In [55]:
b[:,1:3]

array([[10, 40],
       [95, 28],
       [25, 28],
       [67, 83],
       [54,  3]])

In [56]:
b[1:4,1:4]

array([[95, 28, 94],
       [25, 28, 71],
       [67, 83, 28]])

### Subsetting

In [57]:
b[b>50]

array([79, 95, 94, 72, 73, 71, 67, 83, 54, 71, 89])

In [58]:
b>50

array([[ True, False, False, False, False],
       [False,  True, False,  True,  True],
       [ True, False, False,  True, False],
       [False,  True,  True, False, False],
       [False,  True, False,  True,  True]])

## Padding

In [59]:
np.pad(b,pad_width=1,mode='constant',constant_values=1)

array([[ 1,  1,  1,  1,  1,  1,  1],
       [ 1, 79, 10, 40,  8, 37,  1],
       [ 1, 11, 95, 28, 94, 72,  1],
       [ 1, 73, 25, 28, 71, 43,  1],
       [ 1, 25, 67, 83, 28, 47,  1],
       [ 1, 50, 54,  3, 71, 89,  1],
       [ 1,  1,  1,  1,  1,  1,  1]])

## Universal Function

In [60]:
mat1=np.array(nr.randint(1,10,9).reshape(3,3))
mat2=np.array(nr.randint(1,10,9).reshape(3,3))

In [61]:
print("Matrix first :\n ",'-'*40,"\n",mat1)
print("Matrix second :\n ",'-'*40,"\n",mat2)
print("Addition:\n",'-'*50,'\n',mat1+mat2)
print("Subtraction:\n",'-'*50,'\n',mat1-mat2)
print("Multiplication:\n",'-'*50,'\n',mat1*mat2)
print("Division:\n",'-'*50,'\n',mat1/mat2)

Matrix first :
  ---------------------------------------- 
 [[9 5 8]
 [9 5 9]
 [8 3 1]]
Matrix second :
  ---------------------------------------- 
 [[9 9 2]
 [6 4 3]
 [5 8 1]]
Addition:
 -------------------------------------------------- 
 [[18 14 10]
 [15  9 12]
 [13 11  2]]
Subtraction:
 -------------------------------------------------- 
 [[ 0 -4  6]
 [ 3  1  6]
 [ 3 -5  0]]
Multiplication:
 -------------------------------------------------- 
 [[81 45 16]
 [54 20 27]
 [40 24  1]]
Division:
 -------------------------------------------------- 
 [[1.         0.55555556 4.        ]
 [1.5        1.25       3.        ]
 [1.6        0.375      1.        ]]


In [62]:
print("Linear combination like 3*mat1 + 2*mat2 :\n ",'-'*40,"\n",3*mat1+2*mat2)
print("Adding scalar value like 100 :\n ",'-'*40,"\n",mat1+100)

Linear combination like 3*mat1 + 2*mat2 :
  ---------------------------------------- 
 [[45 33 28]
 [39 23 33]
 [34 25  5]]
Adding scalar value like 100 :
  ---------------------------------------- 
 [[109 105 108]
 [109 105 109]
 [108 103 101]]


In [63]:
print("Cube of Matrix :\n ",'-'*40,"\n",mat1**3)
print("Square root of Matrix :\n ",'-'*40,"\n",pow(mat1,0.5))

Cube of Matrix :
  ---------------------------------------- 
 [[729 125 512]
 [729 125 729]
 [512  27   1]]
Square root of Matrix :
  ---------------------------------------- 
 [[3.         2.23606798 2.82842712]
 [3.         2.23606798 3.        ]
 [2.82842712 1.73205081 1.        ]]


In [64]:
mat1*2

array([[18, 10, 16],
       [18, 10, 18],
       [16,  6,  2]])

## Broadcasting

#### TransPose

In [65]:
a=np.array([[0,1,2,3]])
print(a)

[[0 1 2 3]]


In [66]:
a=a.T

In [67]:
a

array([[0],
       [1],
       [2],
       [3]])

## Array Math

In [68]:
a=np.array(nr.randint(1,10,9)).reshape(3,3)
b=np.array(nr.randint(1,10,9)).reshape(3,3)
print(a,'\n\n\n',b)

[[1 8 7]
 [4 3 4]
 [4 9 6]] 


 [[9 6 7]
 [7 5 5]
 [3 1 8]]


In [69]:
np.sqrt(a)

array([[1.        , 2.82842712, 2.64575131],
       [2.        , 1.73205081, 2.        ],
       [2.        , 3.        , 2.44948974]])

In [70]:
np.exp(a)

array([[2.71828183e+00, 2.98095799e+03, 1.09663316e+03],
       [5.45981500e+01, 2.00855369e+01, 5.45981500e+01],
       [5.45981500e+01, 8.10308393e+03, 4.03428793e+02]])

In [71]:
np.log(a)

array([[0.        , 2.07944154, 1.94591015],
       [1.38629436, 1.09861229, 1.38629436],
       [1.38629436, 2.19722458, 1.79175947]])

In [72]:
np.log10(b)

array([[0.95424251, 0.77815125, 0.84509804],
       [0.84509804, 0.69897   , 0.69897   ],
       [0.47712125, 0.        , 0.90308999]])

In [73]:
np.log10(a)

array([[0.        , 0.90308999, 0.84509804],
       [0.60205999, 0.47712125, 0.60205999],
       [0.60205999, 0.95424251, 0.77815125]])